# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-03 15:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about_us',
            old_name='author',
            new_name='username',
        ),
    ]
