# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-04 00:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_auto_20171103_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about_us',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
