# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-04 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_auto_20171104_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='about_us',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
