# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-05 09:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0007_auto_20171104_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='about_us',
            name='About_us_full_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='about_us',
            name='username',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='xyz', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
