# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-05 09:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0008_auto_20171105_0924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about_us',
            name='About_us_full_name',
        ),
    ]
