# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-10 22:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userprofile', '0009_remove_about_us_about_us_full_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teaching',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('Course', models.CharField(max_length=200)),
                ('Year', models.CharField(max_length=200)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Teach', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
