# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 22:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userprofile', '0010_teaching'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projecting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('Topic', models.CharField(max_length=200)),
                ('Details', models.CharField(max_length=200)),
                ('Year', models.CharField(max_length=200)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Project', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
