# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 16:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0011_projecting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teaching',
            old_name='Course',
            new_name='Branch',
        ),
        migrations.RenameField(
            model_name='teaching',
            old_name='Year',
            new_name='Duration',
        ),
        migrations.AddField(
            model_name='teaching',
            name='Institute',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teaching',
            name='Program',
            field=models.CharField(default='BTech', max_length=200),
            preserve_default=False,
        ),
    ]
