# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 17:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0013_education_experience_publications'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teaching',
            old_name='Branch',
            new_name='Course',
        ),
        migrations.RemoveField(
            model_name='teaching',
            name='Program',
        ),
    ]
