# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 06:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0014_auto_20171118_1717'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about_us',
            old_name='phone',
            new_name='Address',
        ),
        migrations.RemoveField(
            model_name='about_us',
            name='Research_interest',
        ),
        migrations.RemoveField(
            model_name='about_us',
            name='primary_Research_group',
        ),
        migrations.AddField(
            model_name='about_us',
            name='Email',
            field=models.CharField(default='a@b.com', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about_us',
            name='Institute',
            field=models.CharField(default='IIT Guwahati', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about_us',
            name='Name',
            field=models.CharField(default='Prof. ', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about_us',
            name='Phone',
            field=models.CharField(default='+91', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about_us',
            name='ResearchInterest',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
