# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0015_auto_20171119_0641'),
    ]

    operations = [
        migrations.AddField(
            model_name='about_us',
            name='LinkedinURL',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
