# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 13:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userprofile', '0016_about_us_linkedinurl'),
    ]

    operations = [
        migrations.CreateModel(
            name='Awards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('Title', models.CharField(max_length=200)),
                ('Date', models.CharField(max_length=200)),
                ('Issuer', models.CharField(max_length=200)),
                ('Description', models.CharField(max_length=200)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Awards', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
