# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0019_about_us_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='about_us',
            name='scholar',
            field=models.CharField(default='', max_length=400),
            preserve_default=False,
        ),
    ]
